/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as ApiPublicHooksSyncCategoryRouteImport } from './routes/api/public/hooks/sync-category'
import { Route as ApiPublicHooksAutoPostFbRouteImport } from './routes/api/public/hooks/auto-post-fb'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncCategoryRoute =
  ApiPublicHooksSyncCategoryRouteImport.update({
    id: '/api/public/hooks/sync-category',
    path: '/api/public/hooks/sync-category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoPostFbRoute =
  ApiPublicHooksAutoPostFbRouteImport.update({
    id: '/api/public/hooks/auto-post-fb',
    path: '/api/public/hooks/auto-post-fb',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/hooks/auto-post-fb': typeof ApiPublicHooksAutoPostFbRoute
  '/api/public/hooks/sync-category': typeof ApiPublicHooksSyncCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/hooks/auto-post-fb': typeof ApiPublicHooksAutoPostFbRoute
  '/api/public/hooks/sync-category': typeof ApiPublicHooksSyncCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRoute
  '/categories': typeof CategoriesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/product/$slug': typeof ProductSlugRoute
  '/api/public/hooks/auto-post-fb': typeof ApiPublicHooksAutoPostFbRoute
  '/api/public/hooks/sync-category': typeof ApiPublicHooksSyncCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/categories'
    | '/sitemap.xml'
    | '/product/$slug'
    | '/api/public/hooks/auto-post-fb'
    | '/api/public/hooks/sync-category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/categories'
    | '/sitemap.xml'
    | '/product/$slug'
    | '/api/public/hooks/auto-post-fb'
    | '/api/public/hooks/sync-category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/categories'
    | '/sitemap.xml'
    | '/product/$slug'
    | '/api/public/hooks/auto-post-fb'
    | '/api/public/hooks/sync-category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRoute
  CategoriesRoute: typeof CategoriesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductSlugRoute: typeof ProductSlugRoute
  ApiPublicHooksAutoPostFbRoute: typeof ApiPublicHooksAutoPostFbRoute
  ApiPublicHooksSyncCategoryRoute: typeof ApiPublicHooksSyncCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-category': {
      id: '/api/public/hooks/sync-category'
      path: '/api/public/hooks/sync-category'
      fullPath: '/api/public/hooks/sync-category'
      preLoaderRoute: typeof ApiPublicHooksSyncCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-post-fb': {
      id: '/api/public/hooks/auto-post-fb'
      path: '/api/public/hooks/auto-post-fb'
      fullPath: '/api/public/hooks/auto-post-fb'
      preLoaderRoute: typeof ApiPublicHooksAutoPostFbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRoute,
  CategoriesRoute: CategoriesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductSlugRoute: ProductSlugRoute,
  ApiPublicHooksAutoPostFbRoute: ApiPublicHooksAutoPostFbRoute,
  ApiPublicHooksSyncCategoryRoute: ApiPublicHooksSyncCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
